
# Site settings
title: Grafter - Linked Data Machine Tools
email: hello@swirrl.com
description: "Grafter - Linked Data Manufacturing - Industrial-strength RDF production"
#baseurl: "/grafter-docs"
baseurl: ""
url: "http://developer.swirrl.com"

# Build settings
markdown: kramdown
relative_permalinks: true
highlighter: rouge
exclude: [README, Gemfile, Gemfile.lock] # if only this worked

# Stylesheet settings
sass:
    sass_dir: _scss
    style: :compressed
    full_exception: true

# Collections
collections:
    about:
      name: About Grafter
      output: true

    getting-started:
      name: Getting Started
      output: true

    # howto:
    #   name: How To
    #   output: true

    # example:
    #   label: Example
    #   output: false
