
# Site settings
title: Grafter - Open Source suite of tools for high quality Linked Data
email: hello@swirrl.com
description: "Documentation for Grafter"
#baseurl: "/grafter-docs"
baseurl: ""
url: "http://developer.swirrl.com"

# Build settings
markdown: kramdown
relative_permalinks: true
highlighter: rouge
exclude: [README, Gemfile, Gemfile.lock] # if only this worked

# Stylesheet settings
sass:
    sass_dir: _scss
    style: :compressed
    full_exception: true

# Collections
collections:
    about:
      label: About Grafter
      output: true

    quick-start:
      label: Quick Start Guide
      output: true

    howto:
      label: How To
      output: true

    tutorials:
      label: Tutorials
      output: true

